### ISSUE TITLE
iPhone lock screen audio controls not being displayed when using SPTAudioStreamingController

### ISSUE THREAD

**Issue by MchlG** [erdtman/spotify-ios-metadata#11]
## Description
Using SPTAudioStreamingController doesn't make the iPhone lock screen audio controls show up.  I use the following code to start an audio session

      `func setupAudioSession(){

         UIApplication.shared.beginReceivingRemoteControlEvents()

         do {
             try    AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: AVAudioSessionCategoryOptions.mixWithOthers)

             self.becomeFirstResponder()

             do {
                 try AVAudioSession.sharedInstance().setActive(true)
                      print("AVAudioSession is Active")
             } catch let error as NSError {
                      print(error.localizedDescription)

             }
         } catch let error as NSError {
                  print(error.localizedDescription)
         }
      }`

and then once my audio begins I call 

    `func setupLockScreen(){
              let commandCenter = MPRemoteCommandCenter.shared()
              commandCenter.nextTrackCommand.isEnabled = true
              commandCenter.nextTrackCommand.addTarget(self, action:#selector(skipTrack))
              MPNowPlayingInfoCenter.default().nowPlayingInfo = [MPMediaItemPropertyTitle: "TESTING"]
    }`

I have background modes enabled, I am able to play audio in the background without any issue. The only problem i have is that the iPhone lock screen doesn't display any controls, nothing shows up on the lock screen at all that indicates that audio is playing. 

I think this may be because in order for the lock screen controls to show up I need to be using one of the iOS audio players liked AVPlayer or AVAudioPlayer. But then how is does the Spotify app get the lock screen controls to work?

### Versions
iOS SDK version
24

### Severity
minor

## Steps to Reproduce
1. use code I've shown above to start an audio session
2. Use SPTAudioStreamingController to begin playing music from Spotify
3. observe no lock screen controls on iPhone screen

### Actual behaviour
iPhone lock screen controls are not shown when playing audio

### Expected behaviour
audio controls displayed on iPhone lock screen when playing audio

**Comment by erdtman** [comment]
I think you want to report this issue to the [iOS-SDK](https://github.com/spotify/ios-sdk), this is the source code for the metadata library.
